config/routes.rb
Designgroup2::Application.routes.draw do
  resources :homes
  root :to => 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.haml
= form_for @home do |f|
  -if @home.errors.any?
    #error_explanation
      %h2= "#{pluralize(@home.errors.count, "error")} prohibited this home from being saved:"
      %ul
        - @home.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/homes/edit.html.haml
%h1 Editing home

= render 'form'

= link_to 'Show', @home
\|
= link_to 'Back', homes_path

app/views/homes/index.html.haml
:javascript
  var c=document.getElementById("myCanvas");
  var ctx=c.getContext("2d");
  ctx.fillStyle="#FF0000";
  ctx.fillRect(0,0,150,75);
  
%h1 Consider the consequences...
%p How exciting!
%p
  How the 
  %bold hell 
  do you make the page margins larger?
%p
  How
  %strong wonderful
  it all will be!
  %p/
  %h2 Next we learn more
  %ol
    %li How to add a photo gallery
    %li How to make the gallery cool
    %li How to make a complicated background
  %h3
    Where to find
    %strong MY
    website:
  %p
    %a 
      = link_to "DESIGN GROUP INK", 'http://www.designgroupink.com'
    %p
      = image_tag('RefugioPalm.jpg')
    %p  
%p
  %h4 &copy 2011 Design Group, Ink.
  %p/      
  %p/
          

app/views/homes/new.html.haml
%h1 New home

= render 'form'

= link_to 'Back', homes_path

app/views/homes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_home_path(@home)
\|
= link_to 'Back', homes_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	
  <title>Design Group, Ink first web page</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	
</head>
<body>

<%= yield %>

</body>
</html>